apiVersion: v1
kind: Service
metadata:
  name: jemo
  labels:
    app: jemo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  selector:
    app: jemo
  type: LoadBalancer
