apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jemo
spec:
  selector:
    matchLabels:
      app: jemo
  updateStrategy:
      type: RollingUpdate
  serviceName: "jemo"
  replicas: _REPLICAS_
  template:
    metadata:
      labels:
        app: jemo
        aadpodidbinding: "jemo"
    spec:
      containers:
        - name: jemo
          image: eclipse/jemo:1.0.4
          env:
            - name: ECLIPSE_JEMO_CLOUD
              value: "AZURE"
            - name: ECLIPSE_JEMO_HTTP_PORT
              value: "80"
            - name: ECLIPSE_JEMO_HTTPS_PORT
              value: "443"
            - name: ECLIPSE_JEMO_AZURE_RESOURCE_GROUP
              value: "_RESOURCE_GROUP_"
            - name: ECLIPSE_JEMO_AZURE_EVENTHUB
              value: "_EVENT_HUB_"
            - name: ECLIPSE_JEMO_AZURE_DB
              value: "_DB_"
            - name: ECLIPSE_JEMO_AZURE_STORAGE
              value: "_STORAGE_"
            - name: ECLIPSE_JEMO_AZURE_LOG_WORKSPACE
              value: "_LOG_WORKSPACE_"
            - name: ECLIPSE_JEMO_AZURE_KEYVAULT
              value: "_KEYVAULT_"
            - name: ECLIPSE_JEMO_AZURE_MSG_MODEL
              value: "_MSG_MODEL_"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kv-volume
              mountPath: /kv
              readOnly: true
      volumes:
        - name: kv-volume
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds
            options:
              usepodidentity: "false"
              keyvaultname: "_KEYVAULT_"
              keyvaultobjectnames: "clientId;clientSecret;tenantId;encryptionKey"
              keyvaultobjecttypes: "secret;secret;secret;secret"
              resourcegroup: "_RESOURCE_GROUP_"
              subscriptionid: "_SUBSCRIPTION_ID_"
              tenantid: "_TENANT_ID_"