apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jemo
spec:
  selector:
    matchLabels:
      app: jemo
  serviceName: "jemo"
  replicas: _JEMO_REPLICAS_
  template:
    metadata:
      labels:
        app: jemo
    spec:
      containers:
        - name: jemo
          image: eclipse/jemo:1.0.7
          imagePullPolicy: Always
          env:
            - name: ECLIPSE_JEMO_AWS_REGION
              value: "_REGION_"
            - name: ECLIPSE_JEMO_CLOUD
              value: "AWS"
            - name: ECLIPSE_JEMO_HTTP_PORT
              value: "80"
            - name: ECLIPSE_JEMO_HTTPS_PORT
              value: "443"
          ports:
            - containerPort: 80
